import '@styles/globals.css'
import { roboto as font } from '@fonts'
import { NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import clsx from 'clsx'
import Image from 'next/image'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const rootLayoutStyles = {
  bgWrap: 'fixed h-full w-full overflow-hidden z-[-1]',
  bg: 'bg-white dark:bg-transparent',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //TODO: Handle dark mode with cookies
  // let response = NextResponse.next()
  // const cookieStore = cookies()
  // const currentTheme = cookieStore.get('theme')?.value

  // if (!currentTheme) response.cookies.set('theme', 'light')

  return (
    <html
      lang="en"
      // default dark theme
      className={clsx([font.className, 'dark'], {
        // ['dark']: currentTheme === 'dark'
      })}
    >
      <body>
        <div className={rootLayoutStyles.bgWrap}>
          <Image
            src={'/bg.png'}
            alt="bg"
            priority
            fill={true}
            style={{ objectFit: 'cover' }}
          />
        </div>
        <div className={rootLayoutStyles.bg}>{children}</div>
      </body>
    </html>
  )
}
